### ISSUE TITLE
Version inconsistensies

### ISSUE THREAD

**Issue by jollyroger** [AndriiGrytsenko/openssh-ldap-publickey#18]
Dear Author,

Please update version information in `bin/openssh-ldap-builickey` to match repository tag information (it is `0.4.7` however repo tag shows `v1.0`).

Also please use tag annotations (i.e. add messages to your tags) to make tools like `git describe` detect your tags as releases with no additional flags.

Please create new `v1.0.1` release if possible because license information was added to the repository after the repo was tagged.

Thanks.

**Comment by AndriiGrytsenko** [comment]
updated.
